FROM jenkins/jenkins:2.303.2-jdk11
RUN jenkins-plugin-cli --plugins \
        kubernetes:1.30.1 \
        workflow-aggregator \
        git \
        configuration-as-code \
        cloudbees-folder \
        antisamy-markup-formatter \
        build-timeout \
        ssh-agent \
        timestamper \
        ws-cleanup \
        gradle \
        htmlpublisher \
        junit \
        xunit \
        jaxb \
        pipeline-github-lib \
        pipeline-stage-view \
        conditional-buildstep \
        jenkins-multijob-plugin \
        cloudbees-bitbucket-branch-source \
        parameterized-trigger \
        copyartifact \
        subversion \
        ssh-slaves \
        matrix-auth \
        pam-auth \
        ldap \
        active-directory \
        role-strategy \
        authorize-project \
        email-ext \
        emailext-template \
        mailer \
        workflow-job \
        credentials-binding \
        ignore-committer-strategy \
        cctray-xml \
        pipeline-aws \
        prometheus
